# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 285119ba831b56019bac2e451ff5ea12e77f4caa897a9d0d156911e65bf77c4ae026cff5a2d3a0ec28a5529dd415c816102dd563f2d7ec029bc2494043cbd408

test:
  secret_key_base: b7aafaa4fc72ba08fa98dde604a7477f43edf25c5d665ee4c0d67333e2a112dec355ab090fc28699b8175f5f3dde6425cb773a3c3a55e33904765a0c63703d5b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
